# salesanalyse over stores in	Maryland and New Jersey	in the terrytori of Northeast

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\sthef\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sthef\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sthef\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sthef\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sthef\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sthef\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
pf_sales = pd.read_csv("StoreSales.csv")
pf_sales.info()
pf_sales.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  object
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  object
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), object(2)
memory usage: 12.8+ MB

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [4]:
pf_details = pd.read_csv("StoreDetail.csv")
pf_details.info()
pf_details.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    object
 1   State              111 non-null    object
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    object
 4   Region             111 non-null    object
 5   Region Director    111 non-null    object
dtypes: int64(1), object(5)
memory usage: 5.3+ KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [5]:
pf_G = pd.read_csv("ProductCategories.csv")
pf_G.info()
pf_G.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     object
 2   SubcategoryID  52 non-null     object
 3   Subcategory    52 non-null     object
dtypes: int64(1), object(3)
memory usage: 1.8+ KB

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [6]:
pf_Pr = pd.read_csv("Products.csv")
pf_Pr.info()
pf_Pr.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    object
 1   Product        669 non-null    object
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    object
dtypes: int64(1), object(3)
memory usage: 21.0+ KB

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

## Core Marketing Analysis

## Question 1 - What are the store IDs, store manager, and cities for the stores in each assigned sales territory|

In [7]:
NM_stores = pf_details[pf_details['State'].isin(['New Jersey', 'Maryland'])]

NM_stores[['State', 'Territory Manager', 'Store ID', 'Store Location']].sort_values('State')

         State Territory Manager  Store ID       Store Location
43    Maryland      Shruti Reddy       731            Annapolis
44    Maryland      Shruti Reddy       732           Back River
45    Maryland      Shruti Reddy       733            Baltimore
46    Maryland      Shruti Reddy       734           Germantown
47    Maryland      Shruti Reddy       735               Howard
48    Maryland      Shruti Reddy       736        North Harford
49    Maryland      Shruti Reddy       737            Parkville
50    Maryland      Shruti Reddy       738  Queen Anne's County
51    Maryland      Shruti Reddy       739              Ridgely
83  New Jersey         Miami Vue       837             Paterson
82  New Jersey         Miami Vue       836              Passaic
81  New Jersey         Miami Vue       835               Newark
80  New Jersey         Miami Vue       834        New Brunswick
79  New Jersey         Miami Vue       833           Morristown
78  New Jersey         Miami Vue       832            Montclair
77  New Jersey         Miami Vue       831          Jersey City
73  New Jersey         Miami Vue       827              Clifton
75  New Jersey         Miami Vue       829           Hackensack
74  New Jersey         Miami Vue       828          East Orange
84  New Jersey         Miami Vue       838              Trenton
72  New Jersey         Miami Vue       826             Cape May
71  New Jersey         Miami Vue       825              Bayonne
70  New Jersey         Miami Vue       824        Atlantic City
76  New Jersey         Miami Vue       830              Hoboken
85  New Jersey         Miami Vue       839             Vineland

## Question 2 — Monthly Total Revenue by Territory

In [13]:
# Filter data for sales in both territies 
northeast_sales = pf_sales[ pf_sales['Store ID'].isin(NM_stores['Store ID'])]

# Getting city and state information from store details and mergeing with sales table
northeast_sales = northeast_sales.merge(NM_stores[['Store ID', 'Store Location', 'State']], on='Store ID')

In [75]:
# Convert date from text to real datetime 

northeast_sales['Transaction Date'] = pd.to_datetime(northeast_sales['Transaction Date'])

# Extracting Year and Month
northeast_sales['Year']  = northeast_sales['Transaction Date'].dt.year
northeast_sales['Month'] = northeast_sales['Transaction Date'].dt.month

In [76]:
# separate states by territory 

maryland_sales = northeast_sales[northeast_sales['State'] == 'Maryland']
nj_sales  = northeast_sales[northeast_sales['State'] == 'New Jersey']

In [77]:
# Build territory summary

# Dictionary to bild the table before putting it on pandas
summary = {
    'Territory'         : ['Maryland', 'New Jersey'],
    'Total Transactions': [len(maryland_sales), len(nj_sales)],
    'Total Revenue'     : [maryland_sales['Sale Amount'].sum(),  nj_sales['Sale Amount'].sum()]
}

# Making the DataFrame
summary_df = pd.DataFrame(summary)

# Format the numbers to look clean
summary_df['Total Transactions'] = summary_df['Total Transactions'].apply(lambda x: f"{x:,}")
summary_df['Total Revenue'] = summary_df['Total Revenue'].apply(lambda x: f"${x:,.2f}")

summary_df

    Territory Total Transactions   Total Revenue
0    Maryland             89,466  $11,451,615.09
1  New Jersey             38,195   $5,175,405.87

In [89]:
# Monthly revenue summary, one total per store per month

monthly_revenue = northeast_sales.groupby(['State', 'Year', 'Month'],
as_index=False )['Sale Amount'].agg ( Total_Revenue ='sum').sort_values(['State', 'Year', 'Month'])

#
monthly_revenue['Total_Revenue'] = monthly_revenue['Total_Revenue'].apply(lambda x: f"${x:,.2f}")

monthly_revenue

         State  Year  Month Total_Revenue
0     Maryland  2022      1   $190,064.90
1     Maryland  2022      2   $197,529.18
2     Maryland  2022      3   $210,228.48
3     Maryland  2022      4   $179,004.18
4     Maryland  2022      5   $212,028.70
..         ...   ...    ...           ...
91  New Jersey  2025      8   $151,923.99
92  New Jersey  2025      9   $163,449.78
93  New Jersey  2025     10   $250,830.46
94  New Jersey  2025     11   $146,953.33
95  New Jersey  2025     12   $170,994.00

[96 rows x 4 columns]

## Question 3 - Which are the top-performing stores

In [110]:
# Group all Maryland transactions by store groups
Mary_Sale_Report = maryland_sales.groupby(
    ['Store Location', 'Store ID' ], as_index=False
    
# adding all sales together  to then get a individual total revenue by store 
    
    )['Sale Amount'].agg(Total_Revenue='sum'
                         
# Making the raking filter for the data, and ranking from highh to lower 
                         
    ).sort_values('Total_Revenue', ascending=False)

# clean total revenue sales number and add dollar sing 
Mary_Sale_Report['Total_Revenue'] = Mary_Sale_Report['Total_Revenue'].apply(lambda x: f"${x:,.2f}")

Mary_Sale_Report

        Store Location  Store ID  Total_Revenue
5        North Harford       736  $8,708,119.00
3           Germantown       734    $584,675.92
6            Parkville       737    $320,441.24
4               Howard       735    $319,394.58
8              Ridgely       739    $318,511.04
2            Baltimore       733    $310,099.90
1           Back River       732    $303,433.61
7  Queen Anne's County       738    $298,074.49
0            Annapolis       731    $288,865.31

In [111]:
Mary_Sale_Report.head(3)

  Store Location  Store ID  Total_Revenue
5  North Harford       736  $8,708,119.00
3     Germantown       734    $584,675.92
6      Parkville       737    $320,441.24

In [108]:
# Group all Maryland transactions by store groups
Nj_Sale_Report = nj_sales.groupby(
    ['Store Location', 'Store ID' ], as_index=False
    
# adding all sales together  to then get a individual total revenue by store 
    
    )['Sale Amount'].agg(Total_Revenue='sum'
                         
# Making the raking filter for the data, and ranking from highh to lower 
                         
    ).sort_values('Total_Revenue', ascending=False)

# clean total revenue sales number and add dollar sing 
Nj_Sale_Report['Total_Revenue'] = Nj_Sale_Report['Total_Revenue'].apply(lambda x: f"${x:,.2f}")

Nj_Sale_Report

   Store Location  Store ID Total_Revenue
11         Newark       835   $623,163.53
14        Trenton       838   $597,565.68
6         Hoboken       830   $316,775.48
0   Atlantic City       824   $314,513.77
10  New Brunswick       834   $311,056.42
9      Morristown       833   $307,320.52
15       Vineland       839   $306,326.30
3         Clifton       827   $301,703.77
12        Passaic       836   $300,358.95
4     East Orange       828   $299,936.24
7     Jersey City       831   $296,244.33
5      Hackensack       829   $293,676.93
1         Bayonne       825   $292,353.59
2        Cape May       826   $285,704.59
8       Montclair       832   $261,593.20
13       Paterson       837    $67,112.57

In [112]:
Nj_Sale_Report.head(3)

   Store Location  Store ID Total_Revenue
11         Newark       835   $623,163.53
14        Trenton       838   $597,565.68
6         Hoboken       830   $316,775.48

## Question 4 - Comparing costumers and rewards ID who were the top customers in each sales territory?

## Question 5 - What is the number of transactions per month by product category in each assigned territory?

## Question 6 - What is total sales revenue per month by category?

## Question 7 - What is your recommendation for where to focus marketing attention in the next quarter?

## Pick two or more of the questions that you analyzed above to render as a chart using Matplotlib.